// import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/src/ComponentsLayout/dashbord/layoutDashbord/Header";
import Footer from "@/src/ComponentsLayout/dashbord/layoutDashbord/Footer";
export const metadata = {
  title: {
    default: "Zaidi page ",
    template: "%s Zaidi page ",
  },
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
// const inter = Inter({ subsets: ["latin"] });
