import React from "react";

export const metadata = {
  title: " hhhhhh",
  description: "Generated by create next app",
};
const IdComp = () => {
  return (
    <div className=" bg-red-400 h-100vh flex justify-center items-center ">
      ID page
    </div>
  );
};

export default IdComp;
